### ISSUE TITLE
Please give example job workflow for Bamboo

### ISSUE THREAD

**Issue by nottinhill** [TheSharpieOne/karma-bamboo-reporter#4]
I would be interested in an example configuration, e.g. how do you collect the mocha.json - are you using the mocha test parser, etc pp.

**Comment by nottinhill** [comment]
title typo

**Comment by TheSharpieOne** [comment]
Somehow this issue got lost in my notifications... sorry about that.  But yes, this requires the [Bamboo Node.js Support](https://marketplace.atlassian.com/plugins/com.atlassian.bamboo.plugins.bamboo-nodejs-plugin) plugin be added to your bamboo.
One you have that there can you create your tasks.  Depending on what you are using to start your tests, your tasks can look different.  You can execute a command directly via CLI with the bamboo command task or use something like the grunt or gulp tasks that are part of the plugin mentioned above.
Either way, you should eventually be running karma, which will run your and report the results.
After that (usually as final tasks that will always run... seeing how if your tests do not pass, it will prevent other tasks from running unless they are final tasks), you use the Mocha Test Parser task to parse the test.  You can (should) clean up the test file after your done parsing it (via another task).
While there are many ways to do this, here is my specific stage of tasks.

![image](https://cloud.githubusercontent.com/assets/664714/9185758/9a49b086-3f8c-11e5-8f7f-399d04fdb1f8.png)
