### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by silentFred** [TheSharpieOne/karma-bamboo-reporter#5]
Hey there!

Would love to use this little plugin but its failing on me...

27-Aug-2015 18:55:47	Error occurred while running Task 'Read Tests(7)' of type com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.reporter.mocha.
27-Aug-2015 18:55:47	java.lang.NoSuchMethodError: com.atlassian.bamboo.util.BambooFileUtils.calculateRelativePath(Ljava/io/File;Ljava/io/File;)Ljava/lang/String;
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.plugins.nodejs.tasks.mocha.parser.MochaParserTaskType.calculateEffectiveFilePattern(MochaParserTaskType.java:54)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.plugins.nodejs.tasks.mocha.parser.MochaParserTaskType.execute(MochaParserTaskType.java:26)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:216)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:98)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:75)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:181)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:101)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:108)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
27-Aug-2015 18:55:47	        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
27-Aug-2015 18:55:47	        at java.lang.Thread.run(Thread.java:744)

**Comment by TheSharpieOne** [comment]
This appears to be an issue with the bamboo plugin itself.  Please file an issue with them: https://bitbucket.org/atlassian/bamboo-nodejs-plugin/issues

This repo is for the karma plugin that runs in node, not the bamboo plugin that runs in java (the output to provided is java errors).  If this plugin failed to run, it would happen when you ran karma, not when you run the report parser.

Can you verify that a result file is being generated on in the bamboo file system?  The default file name is `mocha.json`.

If not, can you verify that the karma config is set up to include and use this reporter.
```
reporters: ['bamboo'],
plugins: ['karma-bamboo-reporter']
```

**Comment by silentFred** [comment]
@TheSharpieOne I feel like a real genius now! Sorry about this. I can confirm that the file is created locally but I'm not sure about on bamboo. Do you think it's required to pull the mocha.json file out as an artifact? I'll go bug the atlasian guys in the meanwhile =) thanks for responding!

**Comment by TheSharpieOne** [comment]
There is no need to pull the file out as an artifact (I never do).   When I have to debug bamboo errors, I find that it is usually easier when going to the directory where bamboo is running the build (where it puts the repo it checked out) and look to see if things I expect to be there are there (such as the report output file).
