### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by serddmitry** [TheSharpieOne/karma-bamboo-reporter#8]
Please release the project, so that we can use the directory creation done as part of de7db7292b6756705288eb766dce80e121d28e3b

**Comment by TheSharpieOne** [comment]
The project was released on npm including that fix a month ago. I can create a release on github, but npm is the preferred way to install.

**Comment by TheSharpieOne** [comment]
Whoops, my bad, I swear I included that fix in the release... You were right, it was not. Creating a new release now.
